### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/physical_validation#168]
- [ ] add conda instructions on "Installation" page.
- [X] SimulationData.ensemble of type EnsembleData: add information on the sampled ensemble; add explanation about what sorts of data are required (i.e. temperature, volume for NVT, etc) (done but check edits).
- [x] Make it clearer that the provided examples are notebooks that can be downloaded and run - right now, if you click, it shows up as a .html page rather than .ipynb.  Suggested change in #166.  Maybe add a comment at the top of the notebook as well so that people can see if they accidentally click and see it as ipynb so they go back and download?
- [x] Check edits in PR #165 and #167
- [x] Integrator validation page -  put the graphs on same page (would require outputting the data in a data structure).
- [x]  In simulation_data.rst, it's not clear in the lammps snippet what "LAMMPS parser cannot read ensemble definition" means.  Do you mean that because it's not defined, physical_validation.data.EnsembleData needs to be run? called?
- [x] in the gromacs flat file example, where unit data is being input, the *_str and *_conversion keywords could be confusing. Is the conversion the conversion factor from the specified units to the gromacs native units?  What does specifying the string do? Does the string need to match anything to be recognized, or is it just for plotting (which is what I recall?) A little more information in comments would be useful (yes, they could read the function docs, but a bit more information here would be good).

**Comment by ptmerz** [comment]
Closing this since I added

- [ ] add conda instructions on "Installation" page.

to #63 .
