### ISSUE TITLE
Plot of sampled distribution and p-value from kinetic energy validation

### ISSUE THREAD

**Issue by rmatsum836** [shirtsgroup/physical_validation#19]
Hi,

I am using the Maxwell-Boltzmann ensemble validation function to check a system of mine.  When executed, my simulation result fits the Boltzmann distribution quite nicely, but the p-value is low (3.95e-08) and thus the null hypothesis is rejected.  This seems to be contradictory.  I am attaching the Gromacs files I have read in for this function, as well as PDF of the plot produced.  Any insight on this would be appreciated.

Thanks,
Ray Matsumoto

Gromacs files:  [pyrrol_valid.zip](https://github.com/shirtsgroup/physical-validation/files/1455380/pyrrol_valid.zip)

Plot: [KE_val.pdf](https://github.com/shirtsgroup/physical-validation/files/1455414/KE_val.pdf)

**Comment by ptmerz** [comment]
Ray, thank you for your message! I'm looking into it and will get back to you as soon as I have figured out what is going on here.

**Comment by ptmerz** [comment]
Hey Ray, just a short message to let you know that we are working on the issue - but we haven't found the cause of this yet. I'll get back to you as soon as I know more.

**Comment by rmatsum836** [comment]
Hey, thank you for looking into this issue.  I look forward to hearing from you.


On Nov 14, 2017, at 8:53 PM, Pascal Merz <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey Ray, just a short message to let you know that we are working on the issue - but we haven't found the cause of this yet. I'll get back to you as soon as I know more.

**Comment by mrshirts** [comment]
@ptmerz, I think we eventually figured out what the reason was - can you post that here and clear the issue (if it should be cleared!)  We should make sure the documentation reflects how this is handled, and why this is something to watch out for (it might be there already - we've discussed it!)

**Comment by rmatsum836** [comment]
@ptmerz @mrshirts I messed around with `physical-validation` again a few months ago after some changes were made.  I just re-ran `kinetic_energy_distribution` and I am no longer have the issue posted.

**Comment by mrshirts** [comment]
OK, we'll close for now.
