### ISSUE TITLE
Add support for grand and semigrand ensembles

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/physical_validation#31]
Already exists in checkensemble need to port over.

**Comment by ptmerz** [comment]
Just checking in - @tlfobe, @wehs7661 , are you still interested in working on this?

**Comment by tlfobe** [comment]
I'm going to take myself off this, for now, might revisit if it hasn't been addressed when I have a little more free time after my first committee meeting.

**Comment by wehs7661** [comment]
Sorry for the late reply. I'm still interested in this issue but I'll probably start with other simpler issues and invest more time on this after my committee meeting. I would have to familiarize myself with what exactly we want to implement though. @ptmerz /@mrshirts do you have any recommended materials/references that I could get started with before working on this issue? Thanks!

**Comment by mrshirts** [comment]
The implementation of grand and semigrand ensembles is in https://github.com/shirtsgroup/checkensemble, so the statistical mechanics is there.  The grand canonical theory is in appendix A of https://doi.org/10.1021/ct300688p. Semi-grand is a relatively small tweak to grand canonical, and is in the checkensemble code.  So it's really more a coding issue of porting the old algorithms into the new code.

Probably the alchemcial metadynamics paper is higher priority, though.

**Comment by ptmerz** [comment]
Closed via #182 which reenables the `checkensemble` functionality. If any tweaks / extensions are wanted, we should open a new issue.
