### ISSUE TITLE
Parsing molecular masses from [default][atomtypes]

### ISSUE THREAD

**Issue by MatKie** [shirtsgroup/physical_validation#38]
https://github.com/shirtsgroup/physical_validation/blob/c8a5a237f8bbbec722a5f1ccf6f3e1222fea9cbf/physical_validation/util/gromacs_interface.py#L316-L322

Hello everyone,

I ran into problems with the kinetic_energy.equipartition() method and traced it back to parsing the wrong masses from my topology. It seems like the masses are parsed from the [moleculetype][atoms] if possible but the fallback is to take it from the [defaults][atomtypes] section. When falling back to the else statement the fourth value in each line of [defaults][atomtypes] is parsed as molecular masses, however, at least for my topology this is the charge and I actually want to parse the third value ([...].split()[2]).

As I'm using an in-house FF and all of the topology is written by me or colleagues this might be specific to our syntax. However, I looked at some of the ffnonbonded.itp of the amber FF and they also should have run into the same problem (from amber94.ff/ffnonbonded.itp):

> ; name      at.num  mass     charge ptype  sigma      epsilon
> Br          35      79.90    0.0000  A   3.95559e-01  1.33888e+00 ; Converted from parm99.dat 
> C            6      12.01    0.0000  A   3.39967e-01  3.59824e-01
> CA           6      12.01    0.0000  A   3.39967e-01  3.59824e-01

**Comment by ptmerz** [comment]
This should generally indeed be the third rather than the fourth column. Fixed in #148.

Very relevant to #147.
