### ISSUE TITLE
Retire py2 support

### ISSUE THREAD

**Issue by ptmerz** [shirtsgroup/physical_validation#47]
Python 2 is finally out of support 🥳 

There are workarounds in different places of the code to make it compatible with both py2 and py3. We should find these and remove any hacks not needed anymore.

**Comment by ptmerz** [comment]
One such workaround concerns the import statements within the module - this might help solve some of the import issues found in #41.

**Comment by SimonBoothroyd** [comment]
> this might help solve some of the import issues found in #41.

Just to note the import issues highlighted by the lint action in #41 are just formatting issues because the code has not been linted yet.

I plan to fix linting issues such as these in a separate PR once #41 has merged.

**Comment by ptmerz** [comment]
I am not aware of any py2 workarounds still in the code base, although I'm sure there are some. I'm closing this, as py 2 support is officially retired, we don't test for it, and there are no obvious ugly hacks left.
