### ISSUE TITLE
Think about pymbar dependency

### ISSUE THREAD

**Issue by ptmerz** [shirtsgroup/physical_validation#48]
physical_validation has a dependency on pymbar. This is only needed to access the timeseries submodule of pymbar. It seems a bit of an overkill to require the full pymbar package just to decorrelate a few timeseries...

**Comment by ptmerz** [comment]
The current situation is working, so this is not too urgent.

I haven't checked recently, but pymbar used to require the six package, which set in motion a bit of a dependency chain. When integrating physical_validation into the GROMACS testing suite, I had complaints that it shouldn't be necessary to install all these dependencies to be able to run basic tests (without plotting) needed for GROMACS CI. So improving this sooner or later would be nice.

Possible alternative solutions could include:
* Making the timeseries module an independent package (to be discussed with @mrshirts and John Chodera - we once talked about possibly doing this, but never followed up)
* Making the timeseries submodule part of physical_validation. This might not seem like the most elegant of approaches, but it's a very mature submodule, it actually was originally part of `checkensemble`, and licensing shouldn't be a problem (it's under MIT).

**Comment by SimonBoothroyd** [comment]
> Making the timeseries module an independent package (to be discussed with @mrshirts and John Chodera - we once talked about possibly doing this, but never followed up)

+1 for this - we've also spoken about doing this through OpenFF in the past

**Comment by mrshirts** [comment]
Are there other places that could host timeseries analysis?  What are the other options?

**Comment by mrshirts** [comment]
Are there other places that have tools to do these things:

* R community?
* PyTorch / other machine learning places?
* pymc3?

**Comment by ptmerz** [comment]
While working on #220, I noticed that we are also using pymbar's BAR functionality. While I still think that it would be great to extract the timeseries functionality from the pymbar package eventually, physical_validation would still depend on pymbar. I am closing this issue.

**Comment by mrshirts** [comment]
Timeseries as separate functionality would be good eventually, John and I had talked about it many times (and frankly, there's a few more functions that really should be added - the current way to determine the autocorrelation is not so good) but John has (likely rightly) balked as being the main developer.  

If I had some minor support from OMSF for handling release issues, I might be able to do the science stuff, though.  

I probably won't have a chance for a couple of months while I get a glut of grants and papers out.
