### ISSUE TITLE
Add more real-world examples to documentation

### ISSUE THREAD

**Issue by ptmerz** [shirtsgroup/physical_validation#50]
Examples (to be extended):

- [x] Replica exchange
- [ ] Expanded ensemble

**Comment by wehs7661** [comment]
I'm interested in helping this out as well if needed since I might be able to provide some examples of other advanced sampling methods. Is it reasonable to also include examples such as expanded ensemble or Hamiltonian replica exchange?  I'll go through [the paper of physical validation](https://doi.org/10.1371/journal.pone.0202764) or [another earlier paper](https://pubs.acs.org/doi/10.1021/ct300688p) to get a better sense.

**Comment by ptmerz** [comment]
> Is it reasonable to also include examples such as expanded ensemble or Hamiltonian replica exchange?

Yes, and it would be important to document how to do that. For example:
* In temperature replica exchange, we would expect the samples at a specific temperature to have the correct kinetic energy distribution. We would expect samples at neighboring temperatures to show the right ratio of distributions in potential energy and volume.
* In Hamiltonian RE, we would again expect the correct kinetic energy distribution. If we'd want to test the potential energy or volume distributions, we'd need to repeat a simulation at different temperature and/or pressure to be able to compare. The same is true for any type of free energy perturbation methods that include a non-zero lambda. It might even be interesting to test the integrator for some lambda values (e.g. when gradually turning off the pairwise interactions), but that's more of a test of the quality of the MD program than of your simulation.
* Expanded ensemble is pretty much RE in a single simulations, so if you process the samples at different lambda values independently, the same as described above is true. It would be interesting to think whether there are tests that we would expect to pass for the entire extended ensemble run. The answer will depend on what you perturb in your extended ensemble.

**Comment by mrshirts** [comment]
Expanded ensemble in temperature (simulated tempering) would be very useful to have an example for validate, since it can be done in a single simulation, also it's not clear simulated tempering is working correctly in GROMACS now.

**Comment by wehs7661** [comment]
I'll start working on this after addressing other simpler issues. Ideally, I should be able to set up some examples by Feb. 20 or so.

**Comment by ptmerz** [comment]
I think that the new documentation did big steps towards being closer to real-world usage, so I'll close this. Doesn't mean we can't add more examples though :)
