### ISSUE TITLE
Add example for usage with OpenMM

### ISSUE THREAD

**Issue by ptmerz** [shirtsgroup/physical_validation#54]
Usage with OpenMM should work by feeding physical_validation python data structures. We should make sure this works and have examples in the documentation.

**Comment by ocmadin** [comment]
I'm interested in working on this.

**Comment by cwalker7** [comment]
I can help with the OpenMM examples too. I've used the ensemble check on different temperature data from openmmtools parallel tempering simulations.

I made a function in CG_openmm which reads a .nc file from the replica exchange simulation, and performs the ensemble check for different temperature pairs. We might consider migrating some of that to the physical validation package itself. https://github.com/shirtsgroup/cg_openmm/blob/master/cg_openmm/simulation/physical_validation.py

**Comment by ptmerz** [comment]
Great @cwalker7, examples for OpenMM would be really helpful! I'm not sure if @ocmadin is still interested in helping with this - but this is definitely something that two people could work on. More examples is good :)

I also think that examples on how to use physical validation for replica exchange simulations would be really helpful. I would suggest that you could explain what needs to be taken care of (for example, make sure that you are using data points from a specific temperature, not data points from different temperatures). You could then just use OpenMM to add examples to the explanation.

I also think that your script would be a great addition. We could also think about adding the OpenMM units to physical validation, such that users could simply call `units=pv.data.UnitData.units("OpenMM")` instead of defining units by hand. But I think that all that would naturally follow from committing your examples - it will be easier to discuss improvement based on real examples of how you are using the package!

Please feel free to get started and upload a first version whenever you have it - then we can discuss next steps based on that! And please let me know if there's something I can help with!

**Comment by ocmadin** [comment]
I'm still interested in helping with this. It sounds like Chris has a decent working example to start.  Maybe I can come up with a minimal example and build a jupyter notebook around it? Does that sound useful or are there better ways I can use my time?

**Comment by cwalker7** [comment]
@ocmadin Yeah that sounds good - I will focus on the replica exchange example and you can start with the minimal example.

As far as timeline, I can work on this a little next week, and aim to finish the week of 2/8-2/12.

**Comment by ocmadin** [comment]
That timeline sounds good to me too.

**Comment by cwalker7** [comment]
Just to update on this, I should have the first version of the replica exchange example ready by Monday 3/1, sorry for the delay.

As far as files to include, do we want to provide a script that actually sets up and runs the replica exchange simulations, or is the output energy and coordinate .nc files sufficient? I've mostly been using my own package cg_openmm to set up the simulations.

**Comment by ptmerz** [comment]
Closed via #103. We can always add more examples, though :)
