### ISSUE TITLE
Use fancy repo badges

### ISSUE THREAD

**Issue by ptmerz** [shirtsgroup/physical_validation#57]
Once we have our CI up and running, we'll want to have a lot of fancy repo badges 😎

**Comment by SimonBoothroyd** [comment]
For badges for things related to Github Actions: https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository

**Comment by ocmadin** [comment]
I'm interested in helping out with this.

**Comment by ptmerz** [comment]
@ocmadin , is there more to do here? I'm putting this on a milestone for in a week, but feel free to move to another milestone or close if work is done.

**Comment by ptmerz** [comment]
I'll assume this is done. @ocmadin , feel free to reopen if you disagree.
