### ISSUE TITLE
physical_validation needs testing!

### ISSUE THREAD

**Issue by ptmerz** [shirtsgroup/physical_validation#59]
Test coverage right now is close to zero. This is a catch-it-all issue to discuss setting up testing.

**Comment by wehs7661** [comment]
I'm still interested and will start working on this by Feb. 12. Should be able to contribute to some unit tests before Feb. 15 or so.

**Comment by ptmerz** [comment]
This is on Feb 15 milestone to check progress, closing this issue will definitely take a bit longer.

**Comment by ptmerz** [comment]
I am closing this 🎉  We have a code coverage of over 90% now through a combination of regression and unit tests. I feel that we can now have reasonable confidence that code changes don't break things if the tests pass. Clearly, we should keep thinking about testing, especially by covering new code, and writing tests if we find corner cases that were not covered.
