### ISSUE TITLE
License discussion

### ISSUE THREAD

**Issue by mattwthompson** [shirtsgroup/physical_validation#62]
From #40:

> SB:  was there a particular reason to go with LGPL rather than something like MIT?

> PM: Part of the code is currently in the GROMACS repo - the package was shipped with GROMACS before it became a stand-alone package and has not yet been removed. (When we have a stable release, I'll make sure that GROMACS gets the package from pip rather than shipping an outdated version.) At the time, we chose the same license as GROMACS to keep things simple.

> MS: Agreed [that licensing can certainly be rediscussed should probably be a separate issue where we can discuss and come to a conclusion]

so here's that issue!

**Comment by ptmerz** [comment]
I just assigned people that were involved in the original discussion to make sure the new issue is noticed - everyone is welcome to chime in here, though!

**Comment by ptmerz** [comment]
Question - what's the advantage of going with something like MIT?

Personally, I like the idea of "keeping open source software open" of (L)GPL type licenses. I wouldn't mind licensing a specific version differently to someone if they'd ask for it and have a good case, but I like the default being "you are using open source software, so you contribute your improvements back to the community". But I'm happy to hear other arguments :)

**Comment by mrshirts** [comment]
Industry users sometimes have issues of using any GPL (or LGPL code), and we want it to be used widely.  But I can ask around a bit more what the current stances are.

**Comment by SimonBoothroyd** [comment]
> Industry users sometimes have issues of using any GPL (or LGPL code), and we want it to be used widely. 

This was mainly what I'd heard as well, but it will probably depend on a case by case basis. 

Just to note that usually to change the license on code, you need to get permission from all authors who have contributed to said code. I.e if anyone beyond @ptmerz and @mrshirts contributed to any of the code here (especially if it was imported from other projects), they would likely need to ok this change also.

**Comment by ptmerz** [comment]
> Just to note that usually to change the license on code, you need to get permission from all authors who have contributed to said code. I.e if anyone beyond @ptmerz and @mrshirts contributed to any of the code here (especially if it was imported from other projects), they would likely need to ok this change also.

That's a very good point. For now, I don't think there has been any contributions from anyone except @mrshirts, myself, and since today @SimonBoothroyd and @mattwthompson, but that will change quickly. So we should better take that decision soon :)

**Comment by mattwthompson** [comment]
I have heard the same things about MIT and tend to default to it. To whatever extent I have voting power, that is my preference among the options.

The three of you are the only one contributors that show up on GitHub at the moment - so unless there is some obscure history out of that scope, approval from the three of you should be sufficient (?)

**Comment by mrshirts** [comment]
I approve changing the license.  I don't mind so much if anyone in industry steals our code, because then it means it's more likely they will be doing simulations correctly.

**Comment by SimonBoothroyd** [comment]
I also agree to the license change.

**Comment by ptmerz** [comment]
I still don't understand the _advantage_ of MIT over LGPL. I don't mind anyone in industry using our code, and LGPL doesn't keep them from doing so. From what I understand, the only thing that LGPL tries to enforce is that if they improve the code, they are supposed to make these changes public, allowing everyone to do simulations more correctly. They can still have their own tool that pulls in functionality from physical_validation if their changes are so secret...

Do I misunderstand something in these licenses, or does it boil down to legal departments of larger companies not understanding how these things work and forbidding anything that sounds like GPL?

**Comment by SimonBoothroyd** [comment]
> or does it boil down to legal departments of larger companies not understanding how these things work and forbidding anything that sounds like GPL?

I think this, or in cases, said legal departments being overcautious. 

Equally happy to keep the current license if you have reservations 🙂

**Comment by ptmerz** [comment]
Let's move to MIT, seems everyone is agreeing with that. Will work on this the coming week.

**Comment by mrshirts** [comment]
Yes, effectively LGPL does keep people from using the code, even though in theory it doesn't.   Gets very complicated when you start putting things in eggs/wheels and embedding them in libraries, and the definitions of "library" start to break down (is my understanding)

**Comment by ptmerz** [comment]
Closed via #69
