### ISSUE TITLE
Review code-level documentation

### ISSUE THREAD

**Issue by ptmerz** [shirtsgroup/physical_validation#65]
This concerns the documentation of the code itself, not accompanying tutorials / manual. Check for completeness, correctness, and accessibility to new developers.

**Comment by mattwthompson** [comment]
I'm not sure what you mean by this - accuracy and completeness of docstrings?

**Comment by ptmerz** [comment]
See that all relevant items have docstrings, and that they are correct. And if possible understandable without a degree in CS 😁
