### ISSUE TITLE
Enable LGTM and Codecov

### ISSUE THREAD

**Issue by SimonBoothroyd** [shirtsgroup/physical_validation#70]
## Description

We should enable the [LGTM](https://lgtm.com/) and [Codecov](https://codecov.io/) services on this repository to gain extra lint checking, and better reporting of the coverage of our unit tests.

Likely a good first issue for @ocmadin, @wehs7661 or @tlfobe.

**Comment by wehs7661** [comment]
Sounds good. I've only used Codecov before but I will look into LGTM.

**Comment by tlfobe** [comment]
Looking into lgtm today, will see if I can add any badges generated by lgtm to the README

**Comment by tlfobe** [comment]
Got a codecov page and a lgtm page going for physical validation:

https://lgtm.com/projects/g/shirtsgroup/physical_validation/ci/

https://codecov.io/gh/shirtsgroup/physical_validation

Adding badges and relevant additions to our continuous_integration.yaml files in this PR #72
