### ISSUE TITLE
kinetic enegy distribution from flatparser

### ISSUE THREAD

**Issue by spheex** [shirtsgroup/physical_validation#76]
Hi everyone,

Thank you for developping this tool!

I'm trying to use it for my simulations carried out using NAMD.
I converted the positions and velocities trajectories into the right format for the flatparser, and it seems working.
I want to check the kinetic energy distribution, and it works UNLESS I specify a filename to display and save the plot...

Here are the code lines I'm using (and work):
```
import physical_validation as pv
import os

ensemble = pv.data.ensemble_data.EnsembleData("NVT", natoms = 219, temperature = 300, volume = 10000)
units = pv.data.unit_data.UnitData(0.001985875, "4.184", "0.1", "0.001", "1", "1", "0.001")
system = pv.data.system_data.SystemData(natoms=219, nconstraints=0,ndof_reduction_tra=0, ndof_reduction_rot=0)
parser =pv.data.flatfile_parser.FlatfileParser()
test = parser.get_simulation_data(units = units, ensemble = ensemble, system = system, dt = 1, position_file = "test_ok.xyz", velocity_file = "vel_ok.xyz", kinetic_ene_file = "kinetic_energy.txt")
pv.kinetic_energy.distribution(test, verbosity = 2, strict = True)
```

If I change the last line for `pv.kinetic_energy.distribution(test, verbosity = 2, filename = "plottest")`, it displays these errors:

`After equilibration, decorrelation and tail pruning, 28.92% (59 frames) of original Kinetic energy remain.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shoyas/miniconda2/envs/ChemCoordEnv/lib/python3.7/site-packages/physical_validation/kinetic_energy.py", line 147, in distribution
    **temp_unit=data.units.temperature_str)**
  File "/home/shoyas/miniconda2/envs/ChemCoordEnv/lib/python3.7/site-packages/physical_validation/util/kinetic_energy.py", line 314, in check_mean_std
    **screen=screen)**
  File "/home/shoyas/miniconda2/envs/ChemCoordEnv/lib/python3.7/site-packages/physical_validation/util/plot.py", line 72, in plot
    **_, x, _ = ax.hist(y, r['hist'], **args)**
  File "/home/shoyas/miniconda2/envs/ChemCoordEnv/lib/python3.7/site-packages/matplotlib/__init__.py", line 1438, in inner
    **return func(ax, *map(sanitize_sequence, args), **kwargs)**
  File "/home/shoyas/miniconda2/envs/ChemCoordEnv/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 6656, in hist
    **m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)**
  File "<__array_function__ internals>", line 6, in histogram
  File "/home/shoyas/miniconda2/envs/ChemCoordEnv/lib/python3.7/site-packages/numpy/lib/histograms.py", line 792, in histogram
    **bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)**
  File "/home/shoyas/miniconda2/envs/ChemCoordEnv/lib/python3.7/site-packages/numpy/lib/histograms.py", line 424, in _get_bin_edges
    **raise ValueError('`bins` must be positive, when an integer')**
ValueError: `bins` must be positive, when an integer`

It seems to always display an error related to the last line of the function involved. For example, in the `/home/shoyas/miniconda2/envs/ChemCoordEnv/lib/python3.7/site-packages/physical_validation/kinetic_energy.py`, the "error" is related to the last line of the `distribution` function.

I really don't understand... 

Could you please help me?

Thank you in advance.

**Comment by ptmerz** [comment]
Hi @spheex,

Thank you for reporting this! Unfortunately, I have not been able to reproduce the error yet. Could you share the `kinetic_energy.txt` you are using? You probably hit some edge-case we never observed, so I'd love to investigate that further!

Thanks again!

**Comment by spheex** [comment]
Thank you for your reply.
You can try exactly what I've done. I provided the three files in the following file:
[for_github.tar.gz](https://github.com/shirtsgroup/physical_validation/files/5664291/for_github.tar.gz)

Thanks again!

**Comment by ptmerz** [comment]
Thanks for the input files, that was helpful! So what happened is that we had set a minimum amount of data points to plot a histogram. Your trajectory is very short (at least after equilibration, decorrelation and tail pruning). That is enough to get a good feeling for whether your kinetic energy is correct (looks good!), but it won't make for a very pretty plot.

#77 handles this more gracefully. Feel free to download the branch https://github.com/shirtsgroup/physical_validation/tree/ptmerz-fix-76 if you want to try the fix right away. It will make it into the next version of the package, which we'll probably publish some time in January.

Thanks again for reporting this, and for using the package!
