### ISSUE TITLE
LGTM configuration

### ISSUE THREAD

**Issue by ptmerz** [shirtsgroup/physical_validation#92]
We should probably improve a bit how we're using LGTM.

- [x] Add automatic report in PRs - _done_
- [ ] Exclude generated files - e.g. `physical_validation/_version.py` should not be checked, since we don't want to mess with it
- [ ] The `tests/` folder is excluded by default - are we sure that we want that? Are there obvious cases where we want to do things in `tests/` that will be flagged by LGTM?

**Comment by mattwthompson** [comment]
Agree some files should be excluded (I also don't like seeing linting errors from `setup.py`, etc. while they're working) and also agree should also be linting the test files.

I'm not seeing where the LGTM settings are being stored? I'm used to what MolSSI's cookiecutter ships out, which is a file I don't see here: https://github.com/MolSSI/cookiecutter-cms/blob/e17f22b74b9791b7dea7001c9a436e5ac65e84d9/%7B%7Bcookiecutter.repo_name%7D%7D/.lgtm.yml

**Comment by ptmerz** [comment]
I guess the LGTM configuration file go lost when we applied the cookiecutter in #41. Created one in #95, let's see how the LGTM run for that PR looks.

**Comment by mattwthompson** [comment]
>  The tests/ folder is excluded by default - are we sure that we want that? Are there obvious cases where we want to do things in tests/ that will be flagged by LGTM?


At first, I wasn't sure about this - I thought that if the `path_classifiers:  test:` block is left empty, nothing would be tagged as "test" code. But I dug through several projects and see no alerts in any test code - the chance of this happening are low, so they're probably not getting hit in the MolSSI cookiecutter.
