### ISSUE TITLE
Consider making detect equilibration optional so we can use preprocessed data

### ISSUE THREAD

**Issue by cwalker7** [shirtsgroup/physical_validation#99]
It seems like pymbar detect equilibration is always used for the ensemble validation, which can be quite slow. If we already know the start of the production period and correlation time beforehand, it would be useful to be able to bypass detectEquilibration and just feed in the uncorrelated data to physical validation. For datasets containing on the order of 100,000 points, I've found that detectEquilibration alone can take several hours.

**Comment by ptmerz** [comment]
Sounds like a good idea! Would be good to add some clear explanations / warnings so users get info about what they are doing.
